import sys, os, re, json
S=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0,S)
import schgen
from schgen import render, root_sheet, POWER_NETS
from harp_spec import SHEETS
from kisch import parse, sheet_nets, find, first, prop
from collections import defaultdict
OUT=sys.argv[1] if len(sys.argv)>1 else os.path.join(S,'..','..','hardware','kicad','the_harp')
PROJECT='The Harp'
ROOT_UUID='596641a7-eeca-47a8-9244-68f1910acd88'   # kept from the seed root sheet
# nets per sheet
use=defaultdict(set)
for sh in SHEETS:
    for p in sh.parts:
        for n in p.pins.values():
            if n and n not in POWER_NETS: use[n].add(sh.name)
    for n in sh.flags:
        if n not in POWER_NETS: use[n].add(sh.name)
glob={n for n,s in use.items() if len(s)>1}
# duplicate reference check (same ref allowed only for different units)
seen={}
for sh in SHEETS:
    for p in sh.parts:
        k=(p.ref,p.unit)
        assert k not in seen, ('duplicate',k)
        seen[k]=sh.name
os.makedirs(OUT,exist_ok=True)
for sh in SHEETS:
    open(os.path.join(OUT,sh.fname),'w').write(render(sh,PROJECT,ROOT_UUID,glob))
note=("THE HARP - sympathetic-string digital pedal, 26-Z04-0005. One four-layer main board in a Hammond 125B on the Alchemist/Relic grid; "
      "pots, toggles, LEDs and jacks board-mounted.\nSignal: IN -> K401 -> 1M / 100n -> OPA1656 buffer -> THS4522 ADC driver -> AK4621 -> "
      "STM32H750VBT6 (SAI1) -> AK4621 DAC -> OPA1688 difference amps -> OUT L (via K401) and OUT R.\n"
      "GENERATED by scripts/harp_schematic/build.py (Timekeeper circuits, Relic bypass). Every connection is a label on a pin stub. Run ERC.")
open(os.path.join(OUT,'The Harp.kicad_sch'),'w').write(root_sheet(PROJECT,ROOT_UUID,SHEETS,note))
# ---- verification: re-read every sheet, trace nets, compare with the spec
bad=0; netpins=defaultdict(set)
for sh in SHEETS:
    root=parse(open(os.path.join(OUT,sh.fname)).read())
    pins,labels=sheet_nets(root)
    node_name={}
    for node,labs in labels.items():
        names={l[1] for l in labs if l[0] in('global','local','power') and l[1]!='PWR_FLAG'}
        if len(names)>1: print('SHORT',sh.name,names); bad+=1
        if names: node_name[node]=names.pop()
        elif any(l[0]=='nc' for l in labs): node_name[node]=None
    spec={}
    for p in sh.parts:
        for nb,n in p.pins.items(): spec[(p.ref,nb)]=n
    got={}
    for ref,nb,nm,node in pins:
        v=node_name.get(node,'<unlabelled>')
        if got.get((ref,nb)) not in (None,'<unlabelled>') and v!=got[(ref,nb)]: print('UNIT CONFLICT',ref,nb,v,got[(ref,nb)])
        if (ref,nb) not in got or got[(ref,nb)]=='<unlabelled>': got[(ref,nb)]=v
    for k,n in spec.items():
        if k not in got: print('MISSING PIN',sh.name,k); bad+=1
        elif got[k]!=n: print('MISMATCH',sh.name,k,'spec',n,'got',got[k]); bad+=1
        if n: netpins[n].add(k)
    for k in got:
        if k not in spec: print('EXTRA PIN',sh.name,k); bad+=1
# nets with a single pin (likely a typo) excluding power
for n,ps in sorted(netpins.items()):
    if len(ps)<2 and n not in POWER_NETS: print('SINGLE-PIN NET',n,ps); bad+=1
print('sheets',len(SHEETS),'parts',sum(len(s.parts) for s in SHEETS),'global nets',len(glob),'problems',bad)
